### ISSUE TITLE
need to use the newest version of speechbrain in Chapter10_TTS_.ipynb

### ISSUE THREAD

**Issue by lxt3** [bpbpublications/Building-Transformer-Models-with-PyTorch-2.0#4]
For the TTS task to work using speechbrain, you must install the most recent version of speechbrain:

`BRANCH = 'develop'
!python -m pip install git+https://github.com/speechbrain/speechbrain.git@$BRANCH`

Then, replace

`from speechbrain.pretrained import EncoderClassifier`
with 
`from speechbrain.inference.classifiers import EncoderClassifier`

**Comment by lxt3** [comment]
The same applies to chapter10_Speech_Enchancement.ipynb. Change

`from speechbrain.pretrained import SpectralMaskEnhancement`

to

`from speechbrain.inference.enhancement import SpectralMaskEnhancement`

**Comment by prem28timsina** [comment]
updated
